name: detectra
description: "Detectra is a smart inspection app designed to identify asset defects, streamline audits, and generate reliable reports using AI and cloud processing."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Camera & Media
  camera: ^0.10.6
  path_provider: ^2.1.2
  flutter_image_compress: ^2.2.0

  # Local DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Scan & OCR
  mobile_scanner: ^7.1.4
  google_mlkit_commons: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0

  # Permissions
  permission_handler: ^11.4.0

  image_picker: ^1.0.7
  file_picker: ^8.0.0
  archive: ^3.4.10
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true